### ISSUE TITLE
ardupy can't install BME680

### ISSUE THREAD

**Issue by CVYang** [Seeed-Studio/Seeed_BME680#1]
ERROR: Bad dependency format, please check library.json

**Comment by Pillar1989** [comment]
We don't have ardupy BME680 library yet. but we have bme280 instead. you can try it. @CVYang 
```shell
aip install  Seeed-Studio/seeed-ardupy-bme280 
```

**Comment by CVYang** [comment]
BUT I DON'T HAVE BME280,ONLY BME680, IS IT DIFFICULT TO MAKE BME680 LIBRARY?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seeed-Studio/Seeed_BME680"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月15日(星期四) 晚上6:26
收件人:&nbsp;"Seeed-Studio/Seeed_BME680"<Seeed_BME680@noreply.github.com&gt;;
抄送:&nbsp;"杨方健"<401506102@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Seeed-Studio/Seeed_BME680] ardupy can't install BME680 (#1)



 We don't have ardupy BME680 library yet. but we have bme280 instead. you can try it. @CVYang
 aip installSeeed-Studio/seeed-ardupy-bme280

**Comment by Pillar1989** [comment]
https://www.youtube.com/watch?v=8vWIhDNKeo0&feature=youtu.be @CVYang

**Comment by CVYang** [comment]
hello, I use wio terminal to post data to server but it failed.
it can connect to wifi and in server i can see the post and statu code is 200, but there is no data
the attached file is the code , can you help me to fix it?
the server's scripts is as follows:


#######################
from flask import Flask, request
app = Flask(__name__)


@app.route('/')
def hello_world():
&nbsp; &nbsp; return 'hello world'


@app.route('/test', methods=['POST'])
def test():
&nbsp; &nbsp; print(request.headers)
&nbsp; &nbsp; print(request.form)
&nbsp; &nbsp; #print(request.form['code'])
&nbsp; &nbsp; #print(request.form.get('code'))
&nbsp; &nbsp; #print(request.form.getlist('code'))
&nbsp; &nbsp; return 'welcome'
if __name__ == '__main__':
&nbsp; &nbsp; app.run(host='192.168.1.100',port='8000',debug=True)&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seeed-Studio/Seeed_BME680"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 晚上6:57
收件人:&nbsp;"Seeed-Studio/Seeed_BME680"<Seeed_BME680@noreply.github.com&gt;;
抄送:&nbsp;"杨方健"<401506102@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Seeed-Studio/Seeed_BME680] ardupy can't install BME680 (#1)



 Closed #1.
