### ISSUE TITLE
Temperature values are incorrect

### ISSUE THREAD

**Issue by cbitterfield** [Seeed-Studio/Seeed_BME680#4]
The library is not reading values correctly. Used another library and got a more correct value. Also there are no instructions on setting oversampling or calibration parameters.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Can you provide me with the other repositories you use to help me verify this?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
